apiVersion: v1
kind: PersistentVolume
metadata:
  name: efk-es-pv
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 172.21.243.125
    path: /opt/k8s-pods/data/efk-es