name: Deploy to EKS

on:
  push:
    branches: [dev, test]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}

    - name: Set Namespace and Tag
      id: vars
      run: |
        echo "NAMESPACE=${{ github.ref_name }}" >> $GITHUB_ENV
        echo "TAG=${{ github.ref_name }}" >> $GITHUB_ENV

    - name: Deploy to EKS
      run: |
        kubectl apply -f <(envsubst < k8s/deployment.yaml)
        kubectl apply -f <(envsubst < k8s/service.yaml)
