name: Build, Push and Deploy to Kubernetes

on:
  push:
    branches: [dev,main]
    paths-ignore:
      - 'app.api/**'

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: ./app.api
        file: ./app.api/app.dockerfile
        push: true
        tags: ptd0409/tien-dung-api:${{ github.ref_name }}
  deploy:
    needs: docker-build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Set Namespace and Tag
        id: vars
        run: |
          echo "NAMESPACE=${{ github.ref_name }}" >> $GITHUB_ENV
          echo "TAG=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Deploy to EKS
        run: |
          # Create namespace if it doesn't exist
          kubectl create namespace $NAMESPACE --dry-run=client -o yaml | kubectl apply -f -

          # Deploy app
          kubectl apply -f <(envsubst < k8s/backenddeployment.yaml)
          kubectl apply -f <(envsubst < k8s/backendservice.yaml)
          kubectl apply -f <(envsubst < k8s/ingress.yaml)